### ISSUE TITLE
Print QR code on terminal

### ISSUE THREAD

**Issue by susmitpy** [susmitpy/LocalFileTransfer#7]
To adhere to CLI environments (or when running as a docker container), cannot show the QR code image. 
If there is any way to print the QR code on terminal, it would be great

**Comment by Nazneenp** [comment]
assign me the issue i will contribute to it.

**Comment by susmitpy** [comment]
Sure, Thanks

**Comment by Nazneenp** [comment]
@susmitpy can i remove the img.show and replace it with qr.print_ascii to print the qr code directly in the terminal whats your thought. see the below images for example
![Screenshot from 2024-10-09 15-54-37](https://github.com/user-attachments/assets/5767d0fe-074a-410c-afa7-cc63f11db134)

**Comment by susmitpy** [comment]
Yes @Nazneenp 
That should work, we don't need the img then as well. 
Check if we can reduce dependencies (may not require Pillow) 

Thanks
